create table commune (id integer generated by default as identity, name varchar(255), primary key (id))
create table parish (id integer generated by default as identity, contamination_start date, infection_growth integer not null, name varchar(255), commune_id integer, primary key (id))
alter table parish add constraint FK3kgidqpx0b2dbdmu4nkplxw8m foreign key (commune_id) references commune
